// PaperlessUI.Angular/src/app/layout/navbar/app-navbar.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { RouterLink, RouterLinkActive } from '@angular/router';

@Component({
  selector: 'app-navbar',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [RouterLink, RouterLinkActive],
  templateUrl: './app-navbar.component.html',
  styleUrl: './app-navbar.component.css',
})
export class AppNavbarComponent {}

<nav class="app-navbar">
  <a class="app-navbar__brand" routerLink="/documents">Paperless</a>
  <ul class="app-navbar__links">
    <li>
      <a routerLink="/documents" routerLinkActive="is-active">Documents</a>
    </li>
    <li>
      <a routerLink="/upload" routerLinkActive="is-active">Upload</a>
    </li>
    <li>
      <a routerLink="/search" routerLinkActive="is-active">Search</a>
    </li>
  </ul>
</nav>

// PaperlessUI.React/src/components/layout/AppNavbar.tsx
import { NavLink } from 'react-router-dom';

const navLinkClass = ({ isActive }: { isActive: boolean }): string =>
  `app-navbar__link${isActive ? ' is-active' : ''}`;

export function AppNavbar() {
  return (
    <nav className="app-navbar">
      <NavLink to="/documents" className="app-navbar__brand">
        Paperless
      </NavLink>
      <ul className="app-navbar__links">
        <li>
          <NavLink to="/documents" className={navLinkClass}>
            Documents
          </NavLink>
        </li>
        <li>
          <NavLink to="/upload" className={navLinkClass}>
            Upload
          </NavLink>
        </li>
        <li>
          <NavLink to="/search" className={navLinkClass}>
            Search
          </NavLink>
        </li>
      </ul>
    </nav>
  );
}
